<a href="https://colab.research.google.com/github/rohans2596-bot/Syntecxhub_Project_Numpy/blob/main/Copy_of_NUMPY_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr_1d = np.array([10, 20, 30, 40, 50])


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("First element of 1D array:", arr_1d[0])       # Gets 10
print("Last element of 1D array:", arr_1d[-1])       # Gets 50
print("Slice of array (index 1 to 4):", arr_1d[1:4]) # Gets 20, 30, 40

First element of 1D array: 10
Last element of 1D array: 50
Slice of array (index 1 to 4): [20 30 40]


In [ ]:

data = np.random.randint(1, 100, size=10) # 10 random numbers between 1 and 100
print("Dataset:", data)

print("Sum of array:", np.sum(data))
print("Mean (average):", np.mean(data))
print("Max value:", np.max(data))
print("Standard Deviation:", np.std(data))

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum of columns:", np.sum(matrix, axis=0)) # Sums down vertically
print("Sum of rows:", np.sum(matrix, axis=1))    # Sums across horizontally

Dataset: [95 16 76 45  9 93 15 19  6 37]
Sum of array: 411
Mean (average): 41.1
Max value: 95
Standard Deviation: 33.03165148762623
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]


In [ ]:
# Reshaping
original = np.arange(1, 10)
reshaped = original.reshape(3, 3)
print("Reshaped 3x3 Matrix:\n", reshaped)

broadcasted = reshaped + 10
print("Broadcasted Matrix (+10):\n", broadcasted)

Reshaped 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Broadcasted Matrix (+10):
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:

np.save('my_data.npy', broadcasted)
print("File saved!")

loaded_data = np.load('my_data.npy')
print("Loaded data from file:\n", loaded_data)

File saved!
Loaded data from file:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
import time

size = 1000000

py_list = list(range(size))
start_time = time.time()
sum(py_list)
print("Python List Time:", time.time() - start_time)

np_arr = np.arange(size)
start_time = time.time()
np.sum(np_arr)
print("NumPy Array Time:", time.time() - start_time)

Python List Time: 0.009702444076538086
NumPy Array Time: 0.0011816024780273438
